import json
import os
import re
from abc import ABC, abstractmethod
from functools import cache, cached_property
from pathlib import Path
from typing import Annotated, Any, Generic, TypeVar, overload

from pydantic import (
    AfterValidator,
    AliasPath,
    BaseModel,
    ConfigDict,
    Field,
    computed_field,
    model_validator,
)
from pydantic.alias_generators import to_pascal

from hllrcon import Faction, Role
from hllrcon.data.factions import HLLFaction
from hllrcon.data.roles import HLLRole
from scripts import HLL_METADATA_PATH

T = TypeVar("T")
DictT = TypeVar("DictT", bound=dict[str, Any])
ModelT = TypeVar("ModelT", bound="Model")
ObjectT = TypeVar("ObjectT", bound="Object[Any]")

RE_OBJECT_PATH = re.compile(r"^(?P<path>.+)\.(?P<index>\d+)$")
RE_ASSET_PATH = re.compile(r"^/Game(?P<path>/.+)\.(?P<name>.+)$")
AUTOGENERATED_CONTENT_OUTPUT_PATH = Path("hllrcon/data/loadouts.py")
AUTOGENERATED_CONTENT_START_MARKER = "### START OF AUTOGENERATED CONTENT"
AUTOGENERATED_CONTENT_LOADOUT_TEMPLATE = """
    @class_cached_property
    @classmethod
    def {loadout_id}(cls) -> "Loadout":
        return cls(
            name="{loadout.display_name}",
            faction=Faction.{faction},
            role=Role.{role},
            requires_level={loadout.role_level_requirement},
            items=[{items}
            ],
        )
"""
AUTOGENERATED_CONTENT_LOADOUT_ITEM_TEMPLATE = """
                LoadoutItem(name="{item.loadout_item.weapon.meta_data.display_name}", amount={item.initial_clips}),"""  # noqa: E501


class LoadoutLocation(BaseModel):
    faction: Faction
    filepath: Path
    index: int = 0

    def read(self) -> "HLLTeamLoadouts":
        object_path = self.filepath.as_posix() + "." + str(self.index)
        obj = ObjectReference(object_path=object_path).resolve(
            Object[HLLTeamLoadouts],
        )
        return obj.properties


LOADOUT_LOCATIONS = [
    LoadoutLocation(
        faction=HLLFaction.US,
        filepath=Path("HLL/Content/Blueprints/Loadouts/USLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.GER,
        filepath=Path("HLL/Content/Blueprints/Loadouts/GERLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.RUS,
        filepath=Path("HLL/Content/Blueprints/Loadouts/RUSLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.CW,
        filepath=Path("HLL/Content/Blueprints/Loadouts/COMLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.DAK,
        filepath=Path("HLL/Content/Blueprints/Loadouts/GerDAKLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.B8A,
        filepath=Path("HLL/Content/Blueprints/Loadouts/BritEighthLoadouts"),
    ),
]


class Model(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_pascal,
        validate_by_name=True,
    )


class Resolvable(ABC, Generic[T]):
    @abstractmethod
    def resolve(self) -> T: ...


class Resolver(Model, Resolvable[T], Generic[T]):
    _resolved_value: T | None = None

    @abstractmethod
    def _resolve_value(self) -> T: ...

    @overload
    def resolve(self) -> T: ...
    @overload
    def resolve(self, validation_model_type: type[ModelT]) -> ModelT: ...

    def resolve(self, validation_model_type: type[ModelT] | None = None) -> T | ModelT:
        if self._resolved_value is None:
            self._resolved_value = self._resolve_value()
        if validation_model_type is not None:
            return validation_model_type.model_validate(self._resolved_value)
        return self._resolved_value


@cache
def read_file(path: Path) -> list[Any]:
    content = path.read_text(encoding="utf-8")
    json_content = json.loads(content)
    if not isinstance(json_content, list):
        msg = f"Expected an array in the JSON file: {path}"
        raise TypeError(msg)
    return json_content


def merge_dicts(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = base.copy()
    for key, value in override.items():
        if key in merged and isinstance(merged[key], dict) and isinstance(value, dict):
            merged[key] = merge_dicts(merged[key], value)
        else:
            merged[key] = value
    return merged


class ObjectReference(Resolver[DictT]):
    object_path: str

    def _resolve_value(self) -> DictT:
        match = RE_OBJECT_PATH.match(self.object_path)
        if not match:
            msg = f"Invalid object path: {self.object_path}"
            raise ValueError(msg)
        groupdict = match.groupdict()
        path = HLL_METADATA_PATH / (str(groupdict["path"]) + ".json")
        index = int(groupdict["index"])
        json_content = read_file(path)
        return json_content[index]


class AssetReference(Resolver[DictT]):
    asset_path_name: str
    sub_path_string: str

    def _resolve_value(self) -> DictT:
        match = RE_ASSET_PATH.match(self.asset_path_name)
        if not match:
            msg = f"Invalid asset path: {self.asset_path_name}"
            raise ValueError(msg)
        groupdict = match.groupdict()
        path = HLL_METADATA_PATH / ("HLL/Content/" + str(groupdict["path"]) + ".json")
        json_content = read_file(path)
        return next(obj for obj in json_content if obj.get("Name") == groupdict["name"])


class DataTableEntry(Model):
    data_table: ObjectReference
    row_name: str

    def get(self, model_type: type[ModelT]) -> ModelT:
        data_table = self.data_table.resolve(DataTable[model_type])  # type: ignore[valid-type] # ty:ignore[invalid-type-form]
        row = data_table.rows.get(self.row_name)
        if not row:
            msg = (
                f"Row '{self.row_name}' not found in data table"
                f" '{self.data_table.object_path}'."
            )
            raise ValueError(msg)
        return row


class Object(Model, Generic[ModelT]):
    type: str
    name: str
    properties: ModelT

    @model_validator(mode="before")
    @classmethod
    def inherit_template_properties(cls, data: Any) -> Any:  # noqa: ANN401
        if isinstance(data, dict):
            template_ref = data.get("Template")
            if template_ref is not None:
                template = ObjectReference.model_validate(template_ref).resolve(
                    Object[Any],
                )
                merged_properties = merge_dicts(
                    template.properties,
                    data.get("Properties", {}),
                )
                data["Properties"] = merged_properties
        return data


class Blueprint(Object[Model]):
    class_default_object: ObjectReference

    def get_object(self, object_type: type[ObjectT]) -> ObjectT:
        return self.class_default_object.resolve(object_type)


class DataTable(Object[Model], Generic[ModelT]):
    rows: dict[str, ModelT]


class HLLLoadoutItem(Model):
    display_name: Annotated[
        str,
        Field(validation_alias=AliasPath("DisplayName", "SourceString")),
    ]
    weapon_asset: Annotated[
        AssetReference,
        Field(validation_alias="Weapon", exclude=True),
    ]

    @cached_property
    def weapon(self) -> "HLLWeapon":
        bp = self.weapon_asset.resolve(Blueprint)
        return bp.get_object(Object[HLLWeapon]).properties


class HLLWeapon(Model):
    weapon_meta_data: DataTableEntry

    @cached_property
    def meta_data(self) -> HLLLoadoutItem:
        return self.weapon_meta_data.get(HLLLoadoutItem)


class HLLTeamLoadoutItem(Model):
    loadout_item_datatable_entry: Annotated[
        DataTableEntry,
        Field(validation_alias="LoadoutItem", exclude=True),
    ]
    initial_clips: Annotated[int, AfterValidator(lambda v: max(v, 1))]
    maximum_clips: int

    @computed_field
    def loadout_item(self) -> HLLLoadoutItem:
        return self.loadout_item_datatable_entry.get(HLLLoadoutItem)


class HLLTeamLoadout(Model):
    display_name: Annotated[
        str,
        Field(validation_alias=AliasPath("LoadoutDisplayName", "SourceString")),
    ]
    level_requirement: int
    role_level_requirement: int
    loadout_items: list[HLLTeamLoadoutItem]


class HLLTeamLoadouts(Model):
    rifleman: list[HLLTeamLoadout]
    assault: list[HLLTeamLoadout]
    automatic_rifleman: list[HLLTeamLoadout]
    medic: list[HLLTeamLoadout]
    spotter: list[HLLTeamLoadout]
    support: list[HLLTeamLoadout]
    machine_gunner: list[HLLTeamLoadout]
    anti_tank: list[HLLTeamLoadout]
    engineer: list[HLLTeamLoadout]
    officer: list[HLLTeamLoadout]
    sniper: list[HLLTeamLoadout]
    crewman: list[HLLTeamLoadout]
    tank_commander: list[HLLTeamLoadout]
    army_commander: list[HLLTeamLoadout]
    artillery_observer: list[HLLTeamLoadout]
    artillery_engineer: list[HLLTeamLoadout]
    artillery_support: list[HLLTeamLoadout]

    def items(self) -> list[tuple[Role, list[HLLTeamLoadout]]]:
        return [
            (HLLRole.ARMY_COMMANDER, self.army_commander),
            (HLLRole.OFFICER, self.officer),
            (HLLRole.RIFLEMAN, self.rifleman),
            (HLLRole.ASSAULT, self.assault),
            (HLLRole.AUTOMATIC_RIFLEMAN, self.automatic_rifleman),
            (HLLRole.MEDIC, self.medic),
            (HLLRole.SUPPORT, self.support),
            (HLLRole.MACHINE_GUNNER, self.machine_gunner),
            (HLLRole.ANTI_TANK, self.anti_tank),
            (HLLRole.ENGINEER, self.engineer),
            (HLLRole.TANK_COMMANDER, self.tank_commander),
            (HLLRole.CREWMAN, self.crewman),
            (HLLRole.ARTILLERY_OBSERVER, self.artillery_observer),
            (HLLRole.OPERATOR, self.artillery_engineer),
            (HLLRole.GUNNER, self.artillery_support),
            (HLLRole.SPOTTER, self.spotter),
            (HLLRole.SNIPER, self.sniper),
        ]


def autogenerate_loadouts(loadouts: HLLTeamLoadouts, faction: Faction) -> str:
    content = ""
    for role, loadouts_for_role in loadouts.items():
        for loadout in loadouts_for_role:
            if role is HLLRole.OPERATOR:
                role_name = "OPERATOR"
            elif role is HLLRole.GUNNER:
                role_name = "GUNNER"
            else:
                role_name = role.pretty_name.replace(" ", "_").replace("-", "_").upper()
            loadout_id = (
                f"{faction.short_name}_{role_name}"
                f"_{loadout.display_name.replace(' ', '_').upper()}"
            )

            items = ""
            for item in loadout.loadout_items:
                items += AUTOGENERATED_CONTENT_LOADOUT_ITEM_TEMPLATE.format(item=item)

            content += AUTOGENERATED_CONTENT_LOADOUT_TEMPLATE.format(
                loadout_id=loadout_id,
                faction=faction.short_name,
                role=role_name,
                loadout=loadout,
                items=items,
            )
    return content


def main() -> None:
    if not os.getenv("HLL_METADATA_PATH"):
        msg = "The HLL_METADATA_PATH environment variable is not set."
        raise RuntimeError(msg)

    content_to_add = ""

    for location in LOADOUT_LOCATIONS:
        loadouts = location.read()
        content_to_add += autogenerate_loadouts(loadouts, location.faction)

    output_path = AUTOGENERATED_CONTENT_OUTPUT_PATH
    content = output_path.read_text(encoding="utf-8")

    # Update file contents
    content = content.split(AUTOGENERATED_CONTENT_START_MARKER)[0]
    content += AUTOGENERATED_CONTENT_START_MARKER + "\n"
    content += content_to_add
    output_path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
