import json
import os
import re
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Annotated, Any, Generic, TypeVar, overload

from pydantic import (
    AfterValidator,
    AliasPath,
    BaseModel,
    ConfigDict,
    Field,
    computed_field,
)
from pydantic.alias_generators import to_pascal

from hllrcon import Faction, Role
from scripts import HLL_METADATA_PATH

T = TypeVar("T")
DictT = TypeVar("DictT", bound=dict[str, Any])
ModelT = TypeVar("ModelT", bound="Model")

RE_OBJECT_PATH = re.compile(r"^(?P<path>.+)\.(?P<index>\d+)$")
AUTOGENERATED_CONTENT_OUTPUT_PATH = Path("hllrcon/data/loadouts.py")
AUTOGENERATED_CONTENT_START_MARKER = "### START OF AUTOGENERATED CONTENT"
AUTOGENERATED_CONTENT_LOADOUT_TEMPLATE = """
    @class_cached_property
    @classmethod
    def {loadout_id}(cls) -> "Loadout":
        return cls(
            name="{loadout.display_name}",
            faction=Faction.{faction},
            role=Role.{role},
            requires_level={loadout.role_level_requirement},
            items=[{items}
            ],
        )
"""
AUTOGENERATED_CONTENT_LOADOUT_ITEM_TEMPLATE = """
                LoadoutItem(name="{item.loadout_item.display_name}", amount={item.initial_clips}),"""  # noqa: E501


class LoadoutLocation(BaseModel):
    faction: Faction
    filepath: Path
    index: int = 0

    def read(self) -> "HLLTeamLoadouts":
        object_path = self.filepath.as_posix() + "." + str(self.index)
        obj = Reference(object_path=object_path).resolve(
            Object[HLLTeamLoadouts],
        )
        return obj.properties


LOADOUT_LOCATIONS = [
    LoadoutLocation(
        faction=Faction.US,
        filepath=Path("HLL/Content/Blueprints/Loadouts/USLoadouts"),
    ),
    LoadoutLocation(
        faction=Faction.GER,
        filepath=Path("HLL/Content/Blueprints/Loadouts/GERLoadouts"),
    ),
    LoadoutLocation(
        faction=Faction.RUS,
        filepath=Path("HLL/Content/Blueprints/Loadouts/RUSLoadouts"),
    ),
    LoadoutLocation(
        faction=Faction.CW,
        filepath=Path("HLL/Content/Blueprints/Loadouts/COMLoadouts"),
    ),
    LoadoutLocation(
        faction=Faction.DAK,
        filepath=Path("HLL/Content/Blueprints/Loadouts/GerDAKLoadouts"),
    ),
    LoadoutLocation(
        faction=Faction.B8A,
        filepath=Path("HLL/Content/Blueprints/Loadouts/BritEighthLoadouts"),
    ),
]


class Model(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_pascal,
        validate_by_name=True,
    )


class Resolvable(ABC, Generic[T]):
    @abstractmethod
    def resolve(self) -> T: ...


class Resolver(Model, Resolvable[T], Generic[T]):
    _resolved_value: T | None = None

    @abstractmethod
    def _resolve_value(self) -> T: ...

    @overload
    def resolve(self) -> T: ...
    @overload
    def resolve(self, validation_model_type: type[ModelT]) -> ModelT: ...

    def resolve(self, validation_model_type: type[ModelT] | None = None) -> T | ModelT:
        if self._resolved_value is None:
            self._resolved_value = self._resolve_value()
        if validation_model_type is not None:
            return validation_model_type.model_validate(self._resolved_value)
        return self._resolved_value


class Reference(Resolver[DictT]):
    object_path: str

    def _resolve_value(self) -> DictT:
        match = RE_OBJECT_PATH.match(self.object_path)
        if not match:
            msg = f"Invalid object path: {self.object_path}"
            raise ValueError(msg)
        groupdict = match.groupdict()
        path = HLL_METADATA_PATH / (str(groupdict["path"]) + ".json")
        index = int(groupdict["index"])
        content = path.read_text(encoding="utf-8")
        json_content = json.loads(content)
        if not isinstance(json_content, list):
            msg = f"Expected a list in the JSON file: {self.object_path}"
            raise TypeError(msg)
        return json_content[index]


class DataTableEntry(Model):
    data_table: Reference
    row_name: str

    def get(self, model_type: type[ModelT]) -> ModelT:
        data_table = self.data_table.resolve(DataTable[model_type])  # ty:ignore[invalid-type-form]
        row = data_table.rows.get(self.row_name)
        if not row:
            msg = (
                f"Row '{self.row_name}' not found in data table"
                f" '{self.data_table.object_path}'."
            )
            raise ValueError(msg)
        return row


class Object(Model, Generic[ModelT]):
    type: str
    name: str
    properties: ModelT


class DataTable(Object[Model], Generic[ModelT]):
    rows: dict[str, ModelT]


class HLLLoadoutItem(Model):
    display_name: Annotated[
        str,
        Field(validation_alias=AliasPath("DisplayName", "SourceString")),
    ]


class HLLTeamLoadoutItem(Model):
    loadout_item_datatable_entry: Annotated[
        DataTableEntry,
        Field(validation_alias="LoadoutItem", exclude=True),
    ]
    initial_clips: Annotated[int, AfterValidator(lambda v: max(v, 1))]
    maximum_clips: int

    @computed_field
    def loadout_item(self) -> HLLLoadoutItem:
        return self.loadout_item_datatable_entry.get(HLLLoadoutItem)


class HLLTeamLoadout(Model):
    display_name: Annotated[
        str,
        Field(validation_alias=AliasPath("LoadoutDisplayName", "SourceString")),
    ]
    level_requirement: int
    role_level_requirement: int
    loadout_items: list[HLLTeamLoadoutItem]


class HLLTeamLoadouts(Model):
    rifleman: list[HLLTeamLoadout]
    assault: list[HLLTeamLoadout]
    automatic_rifleman: list[HLLTeamLoadout]
    medic: list[HLLTeamLoadout]
    spotter: list[HLLTeamLoadout]
    support: list[HLLTeamLoadout]
    machine_gunner: list[HLLTeamLoadout]
    anti_tank: list[HLLTeamLoadout]
    engineer: list[HLLTeamLoadout]
    officer: list[HLLTeamLoadout]
    sniper: list[HLLTeamLoadout]
    crewman: list[HLLTeamLoadout]
    tank_commander: list[HLLTeamLoadout]
    army_commander: list[HLLTeamLoadout]
    artillery_observer: list[HLLTeamLoadout]
    artillery_engineer: list[HLLTeamLoadout]
    artillery_support: list[HLLTeamLoadout]

    def items(self) -> list[tuple[Role, list[HLLTeamLoadout]]]:
        return [
            (Role.ARMY_COMMANDER, self.army_commander),
            (Role.OFFICER, self.officer),
            (Role.RIFLEMAN, self.rifleman),
            (Role.ASSAULT, self.assault),
            (Role.AUTOMATIC_RIFLEMAN, self.automatic_rifleman),
            (Role.MEDIC, self.medic),
            (Role.SUPPORT, self.support),
            (Role.MACHINE_GUNNER, self.machine_gunner),
            (Role.ANTI_TANK, self.anti_tank),
            (Role.ENGINEER, self.engineer),
            (Role.TANK_COMMANDER, self.tank_commander),
            (Role.CREWMAN, self.crewman),
            (Role.ARTILLERY_OBSERVER, self.artillery_observer),
            (Role.ARTILLERY_ENGINEER, self.artillery_engineer),
            (Role.ARTILLERY_SUPPORT, self.artillery_support),
            (Role.SPOTTER, self.spotter),
            (Role.SNIPER, self.sniper),
        ]


def autogenerate_loadouts(loadouts: HLLTeamLoadouts, faction: Faction) -> str:
    content = ""
    for role, loadouts_for_role in loadouts.items():
        for loadout in loadouts_for_role:
            role_name = role.pretty_name.replace(" ", "_").replace("-", "_").upper()
            loadout_id = (
                f"{faction.short_name}_{role_name}"
                f"_{loadout.display_name.replace(' ', '_').upper()}"
            )

            items = ""
            for item in loadout.loadout_items:
                items += AUTOGENERATED_CONTENT_LOADOUT_ITEM_TEMPLATE.format(item=item)

            content += AUTOGENERATED_CONTENT_LOADOUT_TEMPLATE.format(
                loadout_id=loadout_id,
                faction=faction.short_name,
                role=role_name,
                loadout=loadout,
                items=items,
            )
    return content


def main() -> None:
    if not os.getenv("HLL_METADATA_PATH"):
        msg = "The HLL_METADATA_PATH environment variable is not set."
        raise RuntimeError(msg)

    content_to_add = ""

    for location in LOADOUT_LOCATIONS:
        loadouts = location.read()
        content_to_add += autogenerate_loadouts(loadouts, location.faction)

    output_path = AUTOGENERATED_CONTENT_OUTPUT_PATH
    content = output_path.read_text(encoding="utf-8")

    # Update file contents
    content = content.split(AUTOGENERATED_CONTENT_START_MARKER)[0]
    content += AUTOGENERATED_CONTENT_START_MARKER + "\n"
    content += content_to_add
    output_path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
