import os
from pathlib import Path

from pydantic import BaseModel

from hllrcon import Faction
from hllrcon.data.factions import HLLFaction
from scripts.extractlib.loader import load_asset, local_to_abs_path
from scripts.extractlib.objects.blueprint_generated_class import BlueprintGeneratedClass
from scripts.extractlib.objects.hll_team_loadouts import HLLTeamLoadouts
from scripts.extractlib.objects.hll_weapon import HLLWeapon
from scripts.extractlib.structs.loadout_item import LoadoutItem

AUTOGENERATED_CONTENT_OUTPUT_PATH = Path("hllrcon/data/loadouts.py")
AUTOGENERATED_CONTENT_START_MARKER = "### START OF AUTOGENERATED CONTENT"
AUTOGENERATED_CONTENT_LOADOUT_TEMPLATE = """
    @class_cached_property
    @classmethod
    def {loadout_id}(cls) -> "HLLLoadout":
        return cls(
            name="{loadout.display_name}",
            faction=HLLFaction.{faction},
            role=HLLRole.{role},
            requires_level={loadout.role_level_requirement},
            items=[{items}
            ],
        )
"""
AUTOGENERATED_CONTENT_LOADOUT_ITEM_TEMPLATE = """
                HLLLoadoutItem(name="{display_name}", amount={item.initial_clips}),"""


class LoadoutLocation(BaseModel):
    faction: Faction
    filepath: Path
    index: int = 0

    def read(self) -> "HLLTeamLoadouts":
        fp = local_to_abs_path(self.filepath)
        return load_asset(fp, HLLTeamLoadouts)


LOADOUT_LOCATIONS = [
    LoadoutLocation(
        faction=HLLFaction.US,
        filepath=Path("HLL/Content/Blueprints/Loadouts/USLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.GER,
        filepath=Path("HLL/Content/Blueprints/Loadouts/GERLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.RUS,
        filepath=Path("HLL/Content/Blueprints/Loadouts/RUSLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.CW,
        filepath=Path("HLL/Content/Blueprints/Loadouts/COMLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.DAK,
        filepath=Path("HLL/Content/Blueprints/Loadouts/GerDAKLoadouts"),
    ),
    LoadoutLocation(
        faction=HLLFaction.B8A,
        filepath=Path("HLL/Content/Blueprints/Loadouts/BritEighthLoadouts"),
    ),
]


def autogenerate_loadouts(loadouts: HLLTeamLoadouts, faction: Faction) -> str:
    content = ""
    for role, loadouts_for_role in loadouts.properties.items():
        for loadout in loadouts_for_role:
            role_name = role.pretty_name.replace(" ", "_").replace("-", "_").upper()
            loadout_id = (
                f"{faction.short_name}_{role_name}"
                f"_{loadout.display_name.source_string.replace(' ', '_').upper()}"
            )

            items = ""
            for item in loadout.loadout_items:
                item_name = (
                    item.loadout_item.get(LoadoutItem)
                    .weapon.load(BlueprintGeneratedClass[HLLWeapon])
                    .get_default_object(HLLWeapon)
                    .properties.weapon_meta_data.get(LoadoutItem)
                    .display_name.source_string
                )
                items += AUTOGENERATED_CONTENT_LOADOUT_ITEM_TEMPLATE.format(
                    item=item,
                    display_name=item_name,
                )

            content += AUTOGENERATED_CONTENT_LOADOUT_TEMPLATE.format(
                loadout_id=loadout_id,
                faction=faction.short_name,
                role=role_name,
                loadout=loadout,
                items=items,
            )
    return content


def main() -> None:
    if not os.getenv("HLL_METADATA_PATH"):
        msg = "The HLL_METADATA_PATH environment variable is not set."
        raise RuntimeError(msg)

    content_to_add = ""

    for location in LOADOUT_LOCATIONS:
        loadouts = location.read()
        content_to_add += autogenerate_loadouts(loadouts, location.faction)

    output_path = AUTOGENERATED_CONTENT_OUTPUT_PATH
    content = output_path.read_text(encoding="utf-8")

    # Update file contents
    content = content.split(AUTOGENERATED_CONTENT_START_MARKER)[0]
    content += AUTOGENERATED_CONTENT_START_MARKER + "\n"
    content += content_to_add
    output_path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
