from enum import StrEnum


class EPlayerRole(StrEnum):
    RIFLEMAN = "EPlayerRole::Rifleman"
    ASSAULT = "EPlayerRole::Assault"
    AUTOMATIC_RIFLEMAN = "EPlayerRole::AutomaticRifleman"
    MEDIC = "EPlayerRole::Medic"
    SPOTTER = "EPlayerRole::Spotter"
    SPECIALIST = "EPlayerRole::Specialist"
    MACHINE_GUNNER = "EPlayerRole::HeavyMachineGunner"
    ANTI_TANK = "EPlayerRole::AntiTank"
    GRENADIER = "EPlayerRole::Grenadier"
    ENGINEER = "EPlayerRole::Engineer"
    SQUAD_LEADER = "EPlayerRole::SquadLeader"
    SNIPER = "EPlayerRole::Sniper"
    CREWMAN = "EPlayerRole::Crewman"
    TANK_COMMANDER = "EPlayerRole::TankCommander"
    SUPPORT = "EPlayerRole::MortarSupport"
    OBSERVER = "EPlayerRole::MortarObserver"
    GUNNER = "EPlayerRole::MortarGunner"
    PILOT = "EPlayerRole::HelicopterPilot"
    LOGISTICS_OFFICER = "EPlayerRole::HelicopterLogisticsOfficer"
    FLIGHT_ENGINEER = "EPlayerRole::HelicopterFlightEngineer"
    HELI_MEDIC = "EPlayerRole::HelicopterMedic"
    COMMANDER = "EPlayerRole::ArmyCommander"
